included:
  - Vulns
excluded:
  - Vulns/Tests
line_length: 180
analyzer_rules:
  - unused_declaration
  - unused_import
  - explicit_self
opt_in_rules:
  - all
disabled_rules:
  - sorted_enum_cases
  - anyobject_protocol
  - closure_body_length
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_types_order
  - inert_defer
  - no_grouping_extension
  - no_magic_numbers
  - opening_brace
  - type_contents_order
  - unused_capture_list
  - vertical_whitespace_between_cases
